apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sccat-kruize-optimization-engine-app-set
  namespace: openshift-gitops
  labels:
    app: sccat-kruize-optimization-engine
    service-type: sccat-kruize-optimization-engine
    cluster: kubernetes.default.svc
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        namespace: openshift-tuning
  template:
    metadata:
      name: 'sccat-kruize-{{cluster}}'
      labels:
        catalogathon: "true"
        app: sccat-kruize-optimization-engine
        service-type: sccat-kruize-optimization-engine
        cluster: kubernetes.default.svc
    spec:
      project: default
      source:
        repoURL: https://github.com/IBM/catalogathon-gitops-run
        targetRevision: main
        path: services/sccat-kruize-optimization-engine/v1/manifests
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

