apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tuning
  labels:
    app.kubernetes.io/name: kruize
    app.kubernetes.io/part-of: kruize-optimization
    sovereign-core/service: kruize
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

