apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-tuning
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: quay.io/metering-proxy
    newName: quay.io/bharathappali/kruize-metering
    newTag: v1