apiVersion: v1
kind: ConfigMap
metadata:
  name: sccat-kruize-metering-config
  namespace: openshift-tuning
data:
  metering_enabled: "true"
  metering_endpoint: "http://metering-proxy.openshift-tuning.svc.cluster.local:8080/api/v1/metering/resources/test-instance-subscription/usage"
  metering_interval: "300"
  metrics_config: |
    {
      "metrics": [
        {
          "name": "kruize.experiments",
          "type": "counter",
          "description": "Number of Kruize experiments"
        }
      ]
    }