apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sccat-kruize-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sccat-kruize-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: sccat-kruize-operator
  namespace: openshift-tuning


