apiVersion: v1
kind: Service
metadata:
  name: sccat-kruize-operator-metrics
  namespace: openshift-tuning
  labels:
    control-plane: sccat-kruize-operator
    app.kubernetes.io/name: sccat-kruize-operator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    control-plane: sccat-kruize-operator


